[package]
name = "wave-collapse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vecgrid = "0.2.2"
thiserror = "1.0.38"
gen-iter = "0.3.0"
rand = "0.8.5"
